##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.2.0-B44] date: [Sun Dec 24 07:21:20 CET 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = h723tcp


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES = \
Src/app_ethernet.c \
Src/ethernetif.c \
Src/main.c \
Src/stm32h7xx_it.c \
Src/syscalls.c \
Src/sysmem.c \
Src/system_stm32h7xx.c \
Src/tcp_echoserver.c \
./BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c \
./BSP/lan8742/lan8742.c \
./STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
./STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
./STM32H7xx_HAL_Driver/Src/Legacy/stm32h7xx_hal_eth.c \
./STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
./STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
./STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
./LwIP/src/core/tcp.c \
./LwIP/src/core/tcp_out.c \
./LwIP/src/core/pbuf.c \
./LwIP/src/core/mem.c \
./LwIP/src/core/memp.c \
./LwIP/src/core/def.c \
./LwIP/src/core/ipv4/ip4.c \
./LwIP/src/core/ipv4/ip4_addr.c \
./LwIP/src/core/netif.c \
./LwIP/src/core/ipv4/ip4_frag.c \
./LwIP/src/core/tcp_in.c \
./LwIP/src/core/ipv4/dhcp.c \
./LwIP/src/core/ipv4/etharp.c \
./LwIP/src/netif/ethernet.c \
./LwIP/src/core/ip.c \
./LwIP/src/core/init.c \
./LwIP/src/core/timeouts.c \
./LwIP/src/core/udp.c \
./LwIP/src/core/ipv4/icmp.c \
./LwIP/src/core/inet_chksum.c \
./LwIP/src/core/ipv4/acd.c


# ASM sources
ASM_SOURCES = \
startup_stm32h723zgtx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# FLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS = \
-D USE_HAL_DRIVER \
-D STM32H723xx


# AS includes
AS_INCLUDES =

# C includes
C_INCLUDES = \
-I Inc \
-I ./LwIP/src/include \
-I ./LwIP/system \
-I ./STM32H7xx_HAL_Driver/Inc \
-I ./cmsis_device_h7/Include \
-I ./CMSIS_6/CMSIS/Core/Include \
-I ./BSP/STM32H7xx_Nucleo \
-I ./BSP/lan8742


WARN = -Wall -Wextra -Wpedantic

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) $(WARN) -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) $(WARN) -std=c99 -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g3 -gdwarf-5
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H723ZGTX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys -specs=nano.specs
LDFLAGS = $(MCU) -T $(LDSCRIPT) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
